import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/node_modules/**',
      'frontend/src/components/ui/**', // generated by the shadcn CLI
      '**/*.config.js',
      // Runs inside mongosh, not Node: `rs`, `db`, `print`, `quit` and `sleep`
      // are shell globals that no Node lint environment knows about.
      'docker/mongo/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ── Backend ────────────────────────────────────────────────────────────────
  {
    files: ['backend/**/*.ts', 'shared/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node },
      parserOptions: { ecmaVersion: 2023, sourceType: 'module' },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': ['error', { allow: ['warn', 'error'] }], // use the pino logger
      eqeqeq: ['error', 'smart'],
      'prefer-const': 'error',
      'no-return-await': 'error',
    },
  },

  // ── Frontend ───────────────────────────────────────────────────────────────
  {
    files: ['frontend/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: { ecmaVersion: 2023, sourceType: 'module', ecmaFeatures: { jsx: true } },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // Seed and script files legitimately print to stdout.
  {
    files: ['backend/src/seed/**/*.ts', '**/scripts/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  prettier,
);
